My_Second_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from login_app import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('login_app.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

login_app/urls.py
from django.urls import path
from login_app import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name='login_app'

urlpatterns = [
    path('',views.index,name='index'),
    path('register/',views.register,name='register'),
    path('login/',views.login_page,name='login'),
    path('user_login/',views.user_login,name='user_login'),
    path('logout/',views.user_logout,name='logout'),
]

urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

login_app/models.py
from django.db import models
from django.contrib.auth.models import User

#username,password,email
# Create your models here.

class UserInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    facebook_id= models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)
    
    def __str__(self):
        return self.user.username
    

login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from login_app.models import UserInfo

class UserForm(forms.ModelForm):
    password= forms.CharField(widget=forms.PasswordInput)
    class Meta():
        model = User
        fields = ('username','password','email')
        
        
class UserInfoForm(forms.ModelForm):   
    class Meta:
        model = UserInfo
        fields = ("facebook_id",'profile_pic')

login_app/views.py
from django.shortcuts import render
from login_app.forms import UserForm,UserInfoForm
from login_app.models import UserInfo

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth.models import User

# Create your views here.

def login_page(request):
    return render(request,'login_app/login.html', context={})

def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        
        user=authenticate(username=username,password=password)
        
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse ('login_app:index'))
            else:
                return HttpResponse("Account is not active!..")
        else:
            return HttpResponse('Username or Password is wrong..!')
    else:
        return HttpResponseRedirect(reverse ('login_app:login'))
    
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse ('login_app:index'))
    
def index(request):
    dict={}
    if request.user.is_authenticated:
        current_user=request.user
        user_id=current_user.id
        user_basic_info=User.objects.get(pk=user_id) 
        user_more_info=UserInfo.objects.get(user__pk=user_id)
        dict={'user_basic_info':user_basic_info,'user_more_info':user_more_info}
        
    return render(request,'login_app/index.html',context=dict)


def register(request):
    registered=False
    if request.method =='POST':
        user_form=UserForm(data=request.POST)
        user_info_form=UserInfoForm(data=request.POST)
        
        if user_form.is_valid() and user_info_form.is_valid():
            user =user_form.save()
            user.set_password(user.password)
            user.save()  
            
            user_info=user_info_form.save(commit=False)
            user_info.user=user
            
            if 'profile_pic' in request.FILES:
                user_info.profile_pic=request.FILES['profile_pic']
                
            user_info.save()
            
            registered=True
                
    
    else:
        user_form = UserForm()
        user_info_form=UserInfoForm()
        
    dict={'user_form':user_form,'user_info_form':user_info_form,'registered':registered}
    
    return render(request,'login_app/register.html',context=dict)

templates/login_app/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{{title}}</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Navbar</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href=" {% url 'login_app:index' %}"
                >Home</a
              >
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a
                class="nav-link"
                aria-current="page"
                href=" {% url 'login_app:logout' %}"
                >Logout</a
              >
            </li>
            {% else %}

            <li class="nav-item">
              <a
                class="nav-link"
                aria-current="page"
                href=" {% url 'login_app:register' %}"
                >Register</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link"
                aria-current="page"
                href=" {% url 'login_app:login' %}"
                >Login</a
              >
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container" style="padding-top: 20px">
      {% block body_block %} {% endblock %}
    </div>
  </body>
</html>

templates/login_app/index.html
{% extends 'login_app/base.html' %} 
{% block body_block %} 
{% if user.is_authenticated %}

<p>Hi {{user_basic_info.username}},</p>
<p>Your Email: {{user_basic_info.email}}</p>

<p><a href="{{user_more_info.facebook_id}}">Facebook Profile</a></p>
<img src="/media/{{user_more_info.profile_pic}}" width="200px" />

{% else %}

<div class="alert alert-primary">You are not logged in!</div>

{% endif %}
{% endblock %}

templates/login_app/login.html
{% extends 'login_app/base.html' %} {% block body_block %}
<h1>Please Login:</h1>
<form action="{% url 'login_app:user_login'%}" method="POST">
  <label for="username">Username:</label>
  <input
    type="text"
    name="username"
    placeholder="Enter Username.."
    class="form-control"
    required
  />
  <label for="password">Password:</label>
  <input
    type="password"
    name="password"
    placeholder="Enter Password.."
    class="form-control"
    required
  />
  {% csrf_token %}
  <br>
  <input type="submit" name="submit" value="Login" class="form-control"/>
</form>
{% endblock %}

templates/login_app/register.html
{% extends 'login_app/base.html' %}
{% load static %}
{% block body_block %}
{% if registered %}
<div class="alert alert-success">Congratulations! Registration Successfull</div>
{% else %}
<form enctype="multipart/form-data" method='POST'>
    {{user_form.as_p}}
    {{user_info_form.as_p}}
    {% csrf_token %}
    <input type="submit" name="submit" value="Register">
</form>
{% endif %}
{% endblock  %}